### ISSUE TITLE
[RCA demo only] Remove dependency on jq from RCA demo's create annotation script

### ISSUE THREAD

**Issue by jasonrhodes** [elastic/opentelemetry-demo#117]
**Only required for the rca_ingress_obs branch**

The `create_release_annotation` script relies on `jq` for response parsing. `jq` is not a native package so we should remove that dependency and replace that response parsing with either something like `cut` or `sed`, or simplify the response handling to only print the HTTP status code. 

**Note:** A quick and dirty example of simply printing the HTTP status code back to the user is here: https://github.com/elastic/opentelemetry-demo/blob/rca_ingress_obs/scripts/rca-demo/post-setup#L33, but it only prints the first line of the HTTP header response, e.g.  

```sh
HTTP/1.1 200 OK
```

This obviously isn't great for debugging _why_ something failed but in a pinch it works ok for letting people know if things succeeded or failed, let me know if you want more details on how it works.

**Comment by benakansara** [comment]
Closed by https://github.com/elastic/opentelemetry-demo/pull/121
