### ISSUE TITLE
What kind of tests exists for the demo

### ISSUE THREAD

**Issue by Killpit** [elastic/opentelemetry-demo#126]
What are the kinds of tests existing in this demo for each of the services in the programming language and if it's possible to add tests whether unit or integration tests if necessary to this demo?

**Comment by rogercoll** [comment]
This repository is a fork of [opentelemetry-demo](https://github.com/open-telemetry/opentelemetry-demo), with the services' code kept in sync with the upstream project. The primary purpose of this fork is to configure Elasticsearch for storing all generated data.

Given this context, the issue you’ve raised might be more appropriate for the upstream community to address. Any tests or changes implemented upstream will be automatically reflected in this fork.
